// Main types file - consolidated and organized
// This file now serves as the main entry point for all types

// Import all types from organized files
import './common'
import './live'
import './recent'
import './events'
import './gifts'
import './ui'
import './api'
import './admin'
import './48'
import './idn'
import './image'
import './jkt48official'
import './jkt48v'
import './multi'
import './recent_detail'
import './showroomAPI'
import './showroomLogin'
import './sorter'
import './stats'
import './watch'
import './database/idol_member'
import './database/showroom'
import './recent/generalLive'
import './recent/gift'
import './recent/logDetail'
import './ui/userDraggable'
